#!/bin/bash
# Script to restore dotfiles

cp bash_profile ~/.bash_profile
cp gitignore_global ~/.gitignore_global
cp gitconfig ~/.gitconfig
cp inputrc ~/.inputrc
cp vimrc ~/.vimrc
cp -r vim/ ~/.vim

ln -s $(pwd)/bin/git/contrib/completion/git-completion.bash ~/bin/
ln -s $(pwd)/bin/git/contrib/completion/git-prompt.sh ~/bin/
ln -s $(pwd)/bin/git-smartlog/git-smartlog.py ~/bin/
